### ISSUE TITLE
problem: import vega_datasets.data as ...

### ISSUE THREAD

**Issue by ijlyttle** [altair-viz/vega_datasets#9]
Please forgive me as I am a Python "newbie" and may be asking an ignorant question.

I would like to be able to use the form:

```python
import vega_datasets.data as data
```

instead of 

```python
from vega_datasets import data
```

My motivation is that I can use something analogous to the first form when using the [`import()` function](https://rstudio.github.io/reticulate/reference/import.html) in the R reticulate package.

If I try this (in Python):

```python
from vega_datasets import data
dir(data)
```

I get (as I expect):

```
['7zip',
 'airports',
 'anscombe',
 'barley',
 ...
 'zipcodes']
```

However, if I try this:

```python
import vega_datasets.data as data2
dir(data2)
```

I get:

```
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

whereas I am hoping to replicate the first behavior.

By contrast, this works as I expect:

```python
import scipy.stats as stats
dir(stats)
```

**Question:** could it be possible for `import vega_datasets.data as data` to work like `from vega_datasets import data`?

Thanks!

**Comment by jakevdp** [comment]
Hi – the two import statements are not equivalent. ``from vega_datasets import data`` will import the ``data`` object from the ``vega_datasets`` module. On the other hand, ``import vega_datasets.data as data`` imports the **module** named ``vega_datasets.data``, rather than the ``data`` object that is within the ``vega_datasets`` module.

Because the ``data`` object used by ``vega_datasets`` is not a module, there's no way that we can make ``import vega_datasets.data as data`` do what you want it to do. It is only possible to import a submodule this way.

The reason it works for ``scipy.stats`` is because ``scipy.stats`` is a module object, not an object defined within the ``scipy`` namespace.

I hope that clears things up!

**Comment by ijlyttle** [comment]
Thanks! Reading your explanation, I should have used the word "hope" instead of "expect" ;)

**Comment by realkrantz** [comment]
When I run

```
import altair as alt
from vega_datasets import data
```

I am getting the error: 

> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-2-2927dab32ecc> in <module>()
>       1 import altair as alt
> ----> 2 from vega_datasets import data
>       3 
>       4 iris = data.iris()
>       5 
> 
> ModuleNotFoundError: No module named 'vega_datasets'

Any thoughts why?

**Comment by ijlyttle** [comment]
It almost looks like the package `vega_datasets` is not installed.

**Comment by realkrantz** [comment]
Thanks, @ijlyttle. How do I install the package vega_datasets?

**Comment by ijlyttle** [comment]
No problem, try this: https://github.com/altair-viz/vega_datasets#installation

**Comment by realkrantz** [comment]
Solved. Thanks, @ijlyttle.
